name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - main  # Or your default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify your Node.js version
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git checkout -b site
        rm -rf *   # Caution: This will delete all files in the current branch's working directory!
        mv path/to/build/* .   # Adjust this path based on where your build script places the files
        git add .
        git commit -m "Deploy updates"
        git push -f origin site
