name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Install and Build 🔧
      run: |
        npm install
        npm run build # Or your build command

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
        token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates this secret to use in actions.
